    <head>
    <?php
        echo $this->headTitle($this->translate('Omelett.es Application'))
            ->setSeparator(' - ')
            ->setAutoEscape(false);
    ?>

    <!-- Meta -->
    <?php
        echo $this->headMeta()
            ->setCharset('utf-8')
            ->appendName('viewport', 'width=device-width, initial-scale=1.0');
    ?>

    <!-- Styles and links -->
    <link rel="shortcut icon" type="image/vnd.microsoft.icon" sizes="16x16 24x24 32x32 64x64" href="<?php echo $this->basePath() . '/favicon.ico' ?>">
    <?php
        echo $this->headLink()->appendStylesheet('//ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/themes/smoothness/jquery-ui.min.css')
            //->appendStylesheet('//maxcdn.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css')
            ->appendStylesheet($this->basePath() . '/css/tactilecrm.css');
    ?>

    <!-- Head Scripts -->
    <?php
        echo $this->headScript()
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->appendFile('//cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.2/modernizr.min.js')
            ->appendFile('//ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js')
            ->appendFile('//ajax.googleapis.com/ajax/libs/jqueryui/1.11.1/jquery-ui.min.js')
            ->appendFile('//maxcdn.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js')
            ->appendFile($this->basePath() . '/js/omelettes/collection.js', 'text/javascript')
            ->appendFile($this->basePath() . '/js/omelettes/time.js', 'text/javascript')
            ->appendFile($this->basePath() . '/js/omelettes/form.js', 'text/javascript')
            ->appendFile($this->basePath() . '/js/omelettes.js', 'text/javascript');
    ?>

    </head>