<div class="row">
    <div class="col-lg-10 col-lg-offset-1">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h2 class="panel-title"><?php echo $this->translate($this->title); ?></h2>
            </div>
            <div class="panel-body">
                <table class="table">
                    <thead>
                        <tr>
                            <th><?php echo $this->translate('Contact Name'); ?></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($this->contacts as $contact): ?>
                        <tr>
                            <td><a href="<?php echo $this->url('contacts', array('action' => 'view', 'id' => $contact->getId())); ?>"><?php echo $contact->getFullName(); ?></a></td>
                        </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
