<?php

$contacts = $this->contacts;

?>
<div class="row">
    <div class="col-lg-9">
        <div class="panel panel-default">
            <div class="panel-heading">
                <?php echo $this->paginationControl($contacts, 'Sliding', 'paginate'); ?>
                <div class="crud pull-right">
                    <a class="btn btn-default" href="<?php echo $this->url('contacts/noid', array('action' => 'new')); ?>"><span class="glyphicon glyphicon-plus"></span> <?php echo $this->translate('New Contact'); ?></a>
                </div>
                <h2 class="panel-title"><?php echo $this->translate($this->title); ?></h2>
            </div>
            <div class="panel-body">
                <?php echo $this->tabulate($contacts); ?>
            </div>
        </div>
    </div>
    <div class="col-lg-3">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Contact Tasks'); ?></h3>
            </div>
            <div class="panel-body">
                <ul class="list-unstyled">
                    <li>
                        <span class="glyphicon glyphicon-upload"></span>
                        <a href="<?php echo $this->url(null); ?>"><?php echo $this->translate('Import Contacts'); ?></a>
                    </li>
                    <li>
                        <span class="glyphicon glyphicon-download"></span>
                        <a href="<?php echo $this->url(null); ?>"><?php echo $this->translate('Export Contacts'); ?></a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Contact Tags'); ?></h3>
            </div>
            <div class="panel-body">
                <ul class="list-inline">
                    <?php foreach ($this->resource->getTags() as $tag): ?>
                    <li>
                        <a class="btn btn-xs btn-default" href="<?php echo $this->url('contacts/noid', array('action' => 'tagged', 'extra' => $this->escapeHtml($tag->getName()))); ?>"><span class="glyphicon glyphicon-tag"></span> <?php echo $this->escapeHtml($tag->getName()); ?></a>
                    </li>
                    <?php endforeach; ?>
                </ul>
            </div>
        </div>
    </div>
</div>
