<?php $item = $this->item; ?>
<div class="row">
    <div class="col-lg-9">
        <div class="panel panel-default">
            <div class="panel-heading">
                <div class="crud pull-right">
                    <a class="btn btn-default" href="<?php echo $this->url('contacts/id', array('action' => 'edit', 'id' => $item->getId())); ?>"><span class="glyphicon glyphicon-pencil"></span> <?php echo $this->translate('Edit'); ?></a>
                    <a class="btn btn-default" href="<?php echo $this->url('contacts/id', array('action' => 'delete', 'id' => $item->getId())); ?>"><span class="glyphicon glyphicon-trash"></span> <?php echo $this->translate('Delete'); ?></a>
                </div>
                <h2 class="panel-title"><?php echo $this->translate($this->title); ?></h2>
            </div>
            <div class="panel-heading">
                <div class="tags">
                    <div class="pull-right">
                        <?php $this->tagForm->setAttribute('action', $this->url('contacts/id', array('action' => 'set-tags'), true)); ?>
                        <?php echo $this->partial('form/inline', array('form' => $this->tagForm)); ?>
                    </div>
                    <?php echo $this->listify($item->getTags(), array('list_class' => 'list-inline', 'list_empty_text' => 'No Tags', 'route_name' => 'contacts/noid')); ?>
                </div>
            </div>
            <div class="panel-body">
                <dl class="dl-horizontal">
                    <dt><?php echo $this->translate('Description'); ?></dt>
                    <dd>
                        <?php echo $this->prettyText($item->getDescription()); ?>
                    </dd>
                    <dt><?php echo $this->translate('Last Contacted'); ?></dt>
                    <dd>
                        <?php echo $this->prettyWhen($item->getLastContacted()); ?>
                    </dd>
                    <dt><?php echo $this->translate('Assigned To'); ?></dt>
                    <dd>
                        <?php echo $this->prettyUser($item->getAssignedTo()); ?>
                    </dd>
                </dl>
                <dl class="authorship text-muted text-right">
                    <dt><span class="glyphicon glyphicon-time"></span> Created</dt>
                    <dd><?php echo $this->prettyTime($item->getCreated()); ?> by <?php echo $this->prettyUser($item->getCreatedBy()); ?></dd>
                    <?php if ($item->getUpdated()->format('U') !== $item->getCreated()->format('U')): ?>
                    <dt>Last Updated</dt>
                    <dd>
                        <?php echo $this->prettyTime($item->getUpdated()); ?>
                        <?php if ($item->getUpdatedBy() !== $item->getCreatedBy()): ?>
                        by <?php echo $this->prettyUser($item->getUpdatedBy()); ?>
                        <?php endif; ?>
                    </dd>
                    <?php endif; ?>
                </dl>
            </div>
        </div>
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Recent Activity and Notes'); ?></h3>
            </div>
            <div class="panel-body">
                <?php $this->noteForm->setAttribute('action', $this->url(null, array('action' => 'add-note'), true)); ?>
                <?php echo $this->partial('form/note', array('form' => $this->noteForm)); ?>
                <?php echo $this->listify($this->notes); ?>
            </div>
        </div>
    </div>
    <div class="col-lg-3">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Contact Methods</h3>
            </div>
            <div class="panel-body">
                <?php echo $this->listify($item->getContactMethods()); ?>
            </div>
        </div>
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Addresses</h3>
            </div>
            <div class="panel-body">
                <?php echo $this->listify($item->getAddresses()); ?>
            </div>
        </div>
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Linked Items</h3>
            </div>
            <div class="panel-body">
                <ul class="list-unstyled">
                    <li>No linked items</li>
                </ul>
            </div>
        </div>
    </div>
</div>
