<?php $item = $this->item; ?>
<div class="row">
    <div class="col-lg-8">
        <div class="panel panel-default">
            <div class="panel-heading">
                <div class="crud pull-right">
                    <a class="btn btn-default" href="<?php echo $this->url(null, array('action' => 'edit', 'id' => $item->getId())); ?>"><span class="glyphicon glyphicon-pencil"></span> <?php echo $this->translate('Edit'); ?></a>
                    <a class="btn btn-default" href="<?php echo $this->url(null, array('action' => 'delete', 'id' => $item->getId())); ?>"><span class="glyphicon glyphicon-trash"></span> <?php echo $this->translate('Delete'); ?></a>
                </div>
                <h2 class="panel-title"><?php echo $this->translate($this->title); ?></h2>
            </div>
            <div class="panel-body">
                <dl class="dl-horizontal">
                    <dt><?php echo $this->translate('Description'); ?></dt>
                    <dd>
                        <?php echo nl2br($this->escapeHtml($item->getDescription())); ?>
                    </dd>
                    <dt><?php echo $this->translate('Last Contacted'); ?></dt>
                    <dd>
                        <?php echo $this->prettyWhen($item->getLastContacted()); ?>
                    </dd>
                    <dt><?php echo $this->translate('Assigned To'); ?></dt>
                    <dd>
                        <?php echo $this->prettyUser($item->getAssignedTo()); ?>
                    </dd>
                </dl>
                <dl class="authorship text-muted text-right">
                    <dt><span class="glyphicon glyphicon-time"></span> Created</dt>
                    <dd><?php echo $this->prettyTime($item->getCreated()); ?> by <?php echo $this->prettyUser($item->getCreatedBy()); ?></dd>
                    <?php if ($item->getUpdated()->format('U') !== $item->getCreated()->format('U')): ?>
                    <dt>Last Updated</dt>
                    <dd>
                        <?php echo $this->prettyTime($item->getUpdated()); ?>
                        <?php if ($item->getUpdatedBy() !== $item->getCreatedBy()): ?>
                        by <?php echo $this->prettyUser($item->getUpdatedBy()); ?>
                        <?php endif; ?>
                    </dd>
                    <?php endif; ?>
                </dl>
            </div>
        </div>
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Recent Activity and Notes'); ?></h3>
            </div>
            <div class="panel-body">
                <?php $this->noteForm->setAttribute('action', $this->url(null, array('action' => 'add-note'), true)); ?>
                <?php echo $this->partial('form/note', array('form' => $this->noteForm)); ?>
                <ul class="media-list">
                    <?php if (count($item->getNotes()) < 1): ?>
                    <li class="media">No notes</li>
                    <?php endif; ?>
                    <?php foreach ($item->getNotes() as $note): ?>
                    <?php echo $this->partial($note->getListItemPartial(), array('item' => $note)); ?>
                    <?php endforeach; ?>
                </ul>
            </div>
        </div>
    </div>
    <div class="col-lg-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Contact Methods</h3>
            </div>
            <div class="panel-body">
                <ul class="list-unstyled">
                    <?php if (count($item->getContactMethods()) < 1): ?>
                    <li>No contact methods</li>
                    <?php endif; ?>
                    <?php foreach ($item->getContactMethods() as $contactMethod): ?>
                    <?php echo $this->partial($contactMethod->getListItemPartial(), array('item' => $contactMethod)); ?>
                    <?php endforeach; ?>
                </ul>
            </div>
        </div>
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Addresses</h3>
            </div>
            <div class="panel-body">
                <ul class="list-unstyled">
                    <?php if (count($item->getAddresses()) < 1): ?>
                    <li>No addresses</li>
                    <?php endif; ?>
                    <?php foreach ($item->getAddresses() as $address): ?>
                    <?php echo $this->partial($address->getListItemPartial(), array('item' => $address)); ?>
                    <?php endforeach; ?>
                </ul>
            </div>
        </div>
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Linked Items</h3>
            </div>
            <div class="panel-body">
                <ul class="list-unstyled">
                    <li>No linked items</li>
                </ul>
            </div>
        </div>
    </div>
</div>
