<div class="row">
    <div class="col-lg-6 col-lg-offset-3">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h2 class="panel-title"><?php echo $this->translate($this->title); ?></h2>
            </div>
            <div class="panel-body">
                <p><?php echo $this->translate('You must verify your password in order to continue.'); ?></p>
                <?php echo $this->partial('form/friendly', array('form' => $this->form)); ?>
            </div>
        </div>
    </div>
</div>
