<?php

$fieldset = $this->element;
$typeInput = $fieldset->get('type');
$typeInput->setAttribute('class', 'form-control');
$detailInput = $fieldset->get('detail');
$detailInput->setAttribute('class', 'form-control');
$hasErrors = (boolean)($typeInput->getMessages() || $detailInput->getMessages());

?>

<fieldset<?php echo $fieldset->getAttribute('class') ? ' class="'.$fieldset->getAttribute('class').'"' : ''; ?>>
    <div class="form-group form-group-when<?php echo $hasErrors ? " has-error" : ''; ?>">
        <label class="col-sm-<?php echo $this->labelColWidth; ?> control-label" for="<?php echo $detailInput->getAttribute('id'); ?>">
            <?php echo $fieldset->getLabel(); ?>
        </label>
        <div class="col-sm-<?php echo $this->inputColWidth; ?>">
            <div class="row">
                <div class="col-md-4">
                    <?php echo $this->formSelect($typeInput); ?>
                    <?php echo $this->formElementErrors()->render($typeInput, array('class' => 'help-block list-unstyled')); ?>
                </div>
                <div class="col-md-8">
                    <div class="input-group">
                        <?php echo $this->formText($detailInput); ?>
                        <span class="input-group-addon remove">
                            <span class="glyphicon glyphicon-remove text-danger"></span>
                        </span>
                    </div>
                    <?php echo $this->formElementErrors()->render($detailInput, array('class' => 'help-block list-unstyled')); ?>
                </div>
            </div>
        </div>
    </div>
</fieldset>