<?php

$element = $this->element;
$elementType = $element->getAttribute('type');
if (in_array($elementType, array('email', 'text', 'textarea', 'select', 'password'))) {
	$element->setAttribute('class', 'form-control');
}
if (!$elementType) {
	throw new \Exception('Missing element type for: ' . get_class($element));
}

?>
<?php echo $this->partial(
    'partial/form/friendly/element/' . $elementType . '.phtml',
    array(
        'element'		=> $element,
    )); ?>
