<?php

$element = $this->element;
$elementType = $element->getAttribute('type');
if (!$elementType) {
	throw new \Exception('Missing type for ' . $element->getName() . ' element: ' . get_class($element));
}

?>
<div class="form-group form-group-<?php echo $elementType; ?><?php if ($this->formElementErrors($element)) echo " has-error"; ?><?php if ($element->getOption('group_class')) echo ' ' . $element->getOption('group_class'); ?>">
    <?php echo $this->partial(
        'form/friendly/element',
        array(
            'element' => $element,
        )); ?>
</div>
