<?php

use Omelettes\Tabulate;

$options = $this->options;
$mock = $this->mock;
$data = $this->data;
$colspan = count($mock->getTabulateHeadings());

?>
<form action="<?php echo $this->url($options['base_route'], array('action' => 'process')); ?>">
    <table class="table">
        <thead>
            <tr>
                <?php if ($mock instanceof Tabulate\TabulateItemInterface): ?>
                    <th>
                    </th>
                    <?php foreach ($mock->getTabulateHeadings() as $property => $heading): ?>
                    <th><?php echo $this->escapeHtml($heading); ?></th>
                    <?php endforeach; ?>
                <?php endif; ?>
            </tr>
        </thead>
        <tbody>
            <?php if (count($data) < 1): ?>
            <tr>
                <td></td>
                <td colspan="<?php echo $colspan; ?>">
                    <em><?php echo $this->translate('No results'); ?></em>
                </td>
            </tr>
            <?php endif; ?>
            <?php foreach ($data as $datum): ?>
            <?php if ($datum instanceof Tabulate\TabulateItemInterface): ?>
            <tr>
                <td>
                    <input type="checkbox" name="ids[]" value="<?php echo $datum->getId(); ?>">
                </td>
                <?php echo $this->partial($datum->getTabulateRowPartial(), array('item' => $datum)); ?>
            </tr>
            <?php endif; ?>
            <?php endforeach; ?>
        </tbody>
    </table>
</form>
