<?php

use Omelettes\Tabulatable;

$mock = $this->mock;
$data = $this->data;

?>
<table class="table">
    <thead>
        <tr>
            <?php if ($mock instanceof Tabulatable\TabulatableItemInterface): ?>
                <?php foreach ($mock->getTableHeadings() as $property => $heading): ?>
                <th><?php echo $this->escapeHtml($heading); ?></th>
                <?php endforeach; ?>
            <?php endif; ?>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($data as $datum): ?>
        <?php if ($datum instanceof Tabulatable\TabulatableItemInterface): ?>
        <?php echo $this->partial($datum->getTableRowPartial(), array('item' => $datum)); ?>
        <?php endif; ?>
        <?php endforeach; ?>
    </tbody>
</table>
