<?php

use Omelettes\Form\ViewPartialInterface;
use Zend\Form;

$fieldset = $this->element;

?>
<fieldset<?php echo $fieldset->getAttribute('class') ? ' class="'.$fieldset->getAttribute('class').'"' : ''; ?>>
    <?php foreach ($fieldset as $element): ?>
    <?php

    if ($element instanceof ViewPartialInterface) {
        $partial = $element->getViewPartial();
    } elseif ($element instanceof Form\Fieldset) {
        $partial = 'form/horizontal/fieldset';
    } else {
        $partial = 'form/horizontal/group';
    }
    
    ?>
    <?php echo $this->partial(
        $partial,
        array(
            'element' => $element,
            'labelColWidth' => $this->labelColWidth,
            'inputColWidth' => $this->inputColWidth,
        )); ?>
    <?php endforeach; ?>
</fieldset>