<?php

use Omelettes\Form\ViewPartialInterface;
use Zend\Form;

$collection = $this->element;
$templateElement = $collection->getTemplateElement($collection->getDefaultType());
if ($templateElement instanceof ViewPartialInterface) {
    $partial = $templateElement->getViewPartial();
} elseif ($element instanceof Form\Fieldset) {
    $partial = 'form/horizontal/fieldset';
} else {
    $partial = 'form/horizontal/group';
}

?>
<fieldset class="collection <?php echo $collection->getAttribute('class'); ?>">
    <div class="row">
        <label class="col-sm-<?php echo $this->labelColWidth?> control-label"><?php echo $collection->getLabel(); ?></label>
        <div class="col-sm-<?php echo $this->inputColWidth?>">
            <?php foreach ($collection->getIterator() as $element): ?>
            <?php echo $this->partial(
                $partial,
                array(
                    'element'       => $element,
                    'labelColWidth' => $this->labelColWidth,
                    'inputColWidth' => $this->inputColWidth,
                )); ?>
            <?php endforeach; ?>
            <div class="form-group">
                <div class="col-sm-<?php echo $this->inputColWidth; ?>">
                    <div class="btn-group">
                        <button type="button" class="btn btn-default dropdown-toggle"  data-toggle="dropdown">
                            <span class="glyphicon glyphicon-plus"></span> <?php echo $this->translate('Add ' . $templateElement->getLabel()); ?>
                            <span class="caret"></span><span class="sr-only">Toggle Dropdown</span>
                        </button>
                        <ul class="dropdown-menu" role="menu">
                            <?php foreach ($collection->getTargetMap() as $type => $target): ?>
                            <?php

                            $templateElement = $collection->getTemplateElement($type);
                            if ($templateElement instanceof ViewPartialInterface) {
                                $partial = $templateElement->getViewPartial();
                            } elseif ($element instanceof Form\Fieldset) {
                                $partial = 'form/horizontal/fieldset';
                            } else {
                                $partial = 'form/horizontal/group';
                            }
                            $templateMarkup = $this->partial(
                                $partial,
                                array(
                                    'element'       => $templateElement,
                                    'labelColWidth' => $this->labelColWidth,
                                    'inputColWidth' => $this->inputColWidth,
                                )
                            );
                            
                            ?>
                            <li>
                                <a class="template" href="#" data-index="<?php echo count($collection->getIterator()); ?>" data-type="<?php echo $this->escapeHtmlAttr($type); ?>" data-template="<?php echo $this->escapeHtmlAttr($templateMarkup); ?>"><?php echo $this->translate($collection->getTypeLabel($type)); ?></a>
                            </li>
                            <?php endforeach; ?>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</fieldset>
