<?php echo $this->doctype(); ?>

<!-- Default layout -->
<html lang="en">
    <?php echo $this->partial('html/head'); ?>
    <body class="has-navbar-fixed-top">
        <?php echo $this->partial('navigation/navbar-fixed-top'); ?>
        <?php echo $this->partial('navigation/navbar-fixed-bottom'); ?>
    
        <div class="container">
            <?php echo $this->partial('flash-messenger'); ?>

            <?php echo $this->content; ?>

        </div> <!-- /container -->
    </body>
</html>
