<?php

use OmelettesDoctrine\Document as OmDoc;

$identity = $this->identity();

?>
<nav class="navbar navbar-fixed-bottom navbar-default" role="navigation">
    <div class="container-fluid">
        <div class="collapse navbar-collapse" id="om-bottom-navbar">
            <ul class="nav navbar-nav">
                <li>
                    <a>
                    <span class="glyphicon glyphicon-time"></span>
                    </a>
                </li>
                <?php foreach ($identity->getRememberedRoutes() as $route): ?>
                <li>
                    <a href="<?php echo $this->url($route->getName(), $route->getOptions()); ?>"><?php echo $this->escapeHtml($route->getLabel()); ?></a>
                </li>
                <?php endforeach; ?>
            </ul>
        </div>
    </div>
</nav>
