<?php

use Omelettes\Form as OmForm;
use Zend\Form as ZendForm;

$form = $this->form;
if (!$form->getAttribute('action')) {
    $form->setAttribute('action', $this->url(null, array(), array(), true));
}
$form->setAttribute('class', ($form->getAttribute('class') ? ' ' : '') . 'form-horizontal');
$form->prepare();

$labelColWidth = 2;
$inputColWidth = 10;

?>

<?php echo $this->form()->openTag($form); ?>
<?php foreach ($form as $element): ?>
<?php

if ($element instanceof OmForm\ViewPartialInterface) {
    $partial = $element->getViewPartial();
} elseif ($element instanceof OmForm\Element\MultiTypeCollection) {
    $partial = 'form/horizontal/multitype-collection';
} elseif ($element instanceof ZendForm\Element\Collection) {
    $partial = 'form/horizontal/collection';
} elseif ($element instanceof ZendForm\Fieldset) {
    $partial = 'form/horizontal/fieldset';
} else {
    $partial = 'form/horizontal/group';
}

?>
<?php echo $this->partial(
    $partial,
    array(
        'element' => $element,
        'labelColWidth' => $labelColWidth,
        'inputColWidth' => $inputColWidth,
    )); ?>
<?php endforeach; ?>
<?php echo $this->form()->closeTag($form); ?>
