<?php echo $this->doctype(); ?>

<!-- Default layout -->
<html lang="en">
	<?php echo $this->partial('html/head'); ?>
	<body class="has-navbar-fixed-top">
		<nav class="navbar navbar-fixed-top navbar-front navbar-logo" role="navigation">
			<div class="container-fluid">
				<div class="navbar-header">
					<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#tcrm-front-navbar">
						<span class="sr-only">Toggle navigation</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
					<a class="navbar-brand" href="<?php echo $this->url('front'); ?>">
						<div class="brand-logo">
							<img width="40" height="40" class="img-responsive" src="/img/tactilecrm.svg" alt="Tactile CRM logo">
						</div>
						<?php echo $this->translate('Tactile CRM'); ?>
					</a>
				</div>
				<div class="collapse navbar-collapse" id="tcrm-front-navbar">
					<p class="navbar-text"><?php echo $this->translate('Questions? Call us on +44 (0) 207 183 6677 (M-F 9am-5pm)'); ?></p>
					<div class="navbar-right">
						<a href="<?php echo $this->url('login'); ?>" class="btn btn-default navbar-btn"><?php echo $this->translate('Login'); ?></a>
					</div>
				</div>
			</div>
		</nav>
		
		<div class="container">
			<?php echo $this->partial('flash-messenger'); ?>
			
			<?php echo $this->content; ?>
			
		</div> <!-- /container -->
		
	</body>
</html>
