<?php

$fieldset = $this->element;
$typeInput = $fieldset->get('type');
$hasErrors = $typeInput->getMessages();

$labelInput = $fieldset->get('label');
$labelInput->setAttribute('class', 'form-control');
$defaultInput = $fieldset->get('default');
$defaultInput->setAttribute('class', 'form-control');

$optionsElement = $fieldset->get('options');

?>

<fieldset<?php echo $fieldset->getAttribute('class') ? ' class="'.$fieldset->getAttribute('class').'"' : ''; ?>>
    <div class="form-group form-group-custom-field<?php echo $hasErrors ? " has-error" : ''; ?>">
        <?php echo $this->formHidden($typeInput); ?>
        <label class="control-label col-md-3">
            <?php echo $this->escapeHtml($labelInput->getLabel()); ?>
        </label>
        <div class="col-md-4">
            <div class="input-group">
                <?php echo $this->formText($labelInput); ?>
                <span class="input-group-addon remove">
                    <span class="glyphicon glyphicon-remove text-danger"></span>
                </span>
            </div>
            <?php echo $this->formElementErrors()->render($labelInput, array('class' => 'help-block list-unstyled')); ?>
        </div>
        <label class="control-label col-md-2">
            <?php echo $this->escapeHtml($defaultInput->getLabel()); ?>
        </label>
        <div class="col-md-3">
            <?php echo $this->formSelect($defaultInput); ?>
            <?php echo $this->formElementErrors()->render($defaultInput, array('class' => 'help-block list-unstyled')); ?>
        </div>
    </div>
    
    <?php echo $this->partial('form/horizontal/collection', array('element' => $optionsElement, 'labelColWidth' => 3, 'inputColWidth' => 9)); ?>
</fieldset>