<div class="row">
    <div class="col-lg-6 col-lg-offset-3">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h2 class="panel-title"><?php echo $this->translate($this->title); ?></h2>
            </div>
            <div class="panel-body">
                <?php echo $this->partial('form/friendly', array('form' => $this->form)); ?>
            </div>
        </div>
        <p class="text-center"><?php echo $this->translate("Don't have an account?"); ?> <a href="<?php echo $this->url('signup'); ?>"><?php echo $this->translate('Sign up for FREE today!'); ?></a></p>
    </div>
</div>
